- master/coverage.py
cc @staticfloat @kshyatt we're not currently building coverage for the release branch, so don't think we need to worry too much about compatibility here
> use --precompiled=no instead of deleting sys.so for coverage

- master/coverage.py
The CoverageBase and Coverage syntax has changed. I've updated the buildbot script so everything should run ok now!
> Updated merging coverage files

- master/coverage.py
> Add a force-able builder for coverage?

- master/inventory.py
- master/package_osx.py
- master/package_tarball.py
- master/package_ubuntu.py
- master/package_win.py
See if this results in fewer from-scratch rebuilds
> Try fetching before checkout

- master/coverage.py
Since Julia now writes out `.cov` files with PIDs attached, we don't have to worry about merging things! I tried this over [here](https://codecov.io/github/kshyatt/julia?ref=master) and it works. Should make coverage builds faster since we will no longer need HDF5 as a dependency for them.
> Remove unnecessary stuff!

- master/coverage.py
Sorry, I did something really dumb before. This should work now!
> Actually do the right thing

- master/nightly_gc_debug.py
- master/nightly_threading.py
> Enable tests on the threading buildbot

- master/nightly_threading.py
> Update the option used to enable threading

- master/inventory.py
Hopefully they're all beefy enough to handle this?
Seems silly that we've been building everything in serial all this time.
> Build with -j4 on the buildbots

- master/coverage.py
fix https://github.com/JuliaCI/Coverage.jl/issues/109 (not sure how to test this locally, so this is just a visual change)
> update for changes to Codecov api changes

- master/nightly_gc_debug.py
- master/nightly_threading.py
> do gc_debug in parallel

- master/nightly_llvmsvn.py
(cherry picked from commit 74559433db3cf99d46f375c47d7beca3f542bd24)
The SVN build should finally finish and pass all tests now that my PR is merged a few days ago....
@staticfloat
> Use --startup-file=no instead of -f

- master/package.py
> Remove old `.cov` and `.mem` files

- master/coverage.py
> Updates to coverage collection

- master/package.py
This will supposedly fix our windows woes
> Build `debug` and `release` builds separately

- master/coverage.py
Aka `LOAD_PATH[end - 1]` @staticfloat
> fix path to stdlib

- master/builder_utils.py
This will fix the upload step in https://build.julialang.org/#/builders/93/builds/12 maybe?
> Correctly name the FreeBSD tarball

- master/inventory.py
buildbot version of https://github.com/JuliaLang/julia/pull/28414
test build at https://build.julialang.org/#/builders/83/builds/1950
cc: @staticfloat
> turn AVX512 off on windows

- master/inventory.py
> Add a new worker to freebsdci-test: gaebolg

- master/coverage.py
We are referencing the `Project.toml` in the default environment, not the one CoverageBase provides!
> Update scripts to activate the correct environment

- master/coverage.py
Tested locally on my machine, this works!!
> Finally correct path for stdlib

- master/coverage.py
The Coveralls submit still has that stupid, awful bug.
> Switch ordering of Coveralls and Codecov

- master/coverage.py
> fix hack link direction

- master/coverage.py
> verbosify symlink_fix_cmd

- master/coverage.py
> Coverage.jl deprecations

- master/inventory.py
cc @staticfloat @ararslan 
xref https://github.com/JuliaLang/julia/pull/31046
> FreeBSD CI: make worker Abeing as experimental

- master/coverage.py
@staticfloat is there any way to try this out before merging?
> coverage: use lcov file format

- master/freebsd_ci.py
address https://github.com/JuliaCI/julia-buildbot/pull/106#issuecomment-469521553
cc @staticfloat
> FreeBSDCI: add change filter for scheduler

- master/coverage.py
> I forgot how to write Julia code

- master/coverage.py
> making a dir named mkdir is NOT helpful

- master/nightly_gc_debug.py
This will help ensure that `make debug` still works.
> Make the `GC_DEBUG` nightly build julia nightly as well

- master/separated_testing.py
This is probably going to break everything horribly.
> Run all tests, even those that require network connectivity

- master/doctest.py
- master/master.cfg
Fixes https://github.com/JuliaCI/julia-buildbot/issues/115
> Add `doctest_linux64`

- master/llvmpasses.py
- master/master.cfg
> Add `llvmpasses_linux64` builder

- master/separated_testing.py
This might save us a few minutes of time, if it works.
> Attempt to parallelize download tests alongside the rest of our tests

- master/master.cfg
- master/whitespace.py
> Add `whitespace_linux32` checker

- master/package.py
> Add Windows signing again

- master/package.py
@ViralBShah this should address the feedback we got at JuliaCon
> Add signing of internal `julia.exe`

- master/master.cfg
Fixes doc deployment problems on RC tags
> RC tags should be considered protected as well

- master/builder_utils.py
@staticfloat 
In reference to
https://github.com/JuliaLang/julia/pull/33375
> Update installer extraction for INNO Setup

- master/builder_utils.py
This should hopefully alleviate https://github.com/JuliaCI/julia-buildbot/issues/133
> Ensure all disk images are unmounted both before and after macOS build

- master/inventory.py
> limit to 3 threads on ARM

- master/coverage.py
> fix analyse_and_submit_cov_cmd handling of "

- master/github_listener.py
> Override github pull request handling to use merge commits

- master/coverage.py
> Change CoverageBase to use a URL

- master/separated_testing.py
This should auto-upload `.dmp` files when our windows buildbots get stuck on a test suite for more than 2 hours at a time.
> Add auto-dumping to windows testing regime

- master/package.py
> Add windows installer exe stage

- master/inventory.py
See https://github.com/JuliaCI/julia-buildbot/issues/148
cc. @staticfloat
> Switch march to mcpu for ARM

- master/builder_utils.py
- master/package.py
> Upload tarball versions of Julia binary distribution for all platforms

- master/analyzegc.py
- master/doctest.py
- master/github_listener.py
- master/llvmpasses.py
- master/master.cfg
- master/package.py
- master/whitespace.py
This is an attempt to solve https://github.com/JuliaLang/julia/pull/36123#issuecomment-637866771
> Don't skip whitespace checker during `[ci skip]`

- commands/tar2zip.py
- master/builder_utils.py
- master/master.cfg
- master/package.py
@staticfloat 
I'm working on getting zip's of the Windows installer's uploaded.
My strategy is to use a python script to convert the tarballs we already generate to zip files and then upload these. 
I don't know how to test this, so would love some help finalizing things. I think everything should be ok, except the `FileUpload` step which I haven't figured out how to get working (help here is appreciated!)
> Upload portable zip installer on Windows

- master/analyzegc.py
@keno I believe this is what you asked for?
> Add `clangsa` pass to `analyzegc` run

- master/package.py
This is a stop-gap solution, until we can figure out what's wrong with the other signer. 
Semi reverts part of
https://github.com/JuliaCI/julia-buildbot/commit/c4c2ec396e5399dbf17edb2f3fadd8c0b4308ee6#diff-ab12f6414ce89b2ce5abd65eda9d93ddL198
> Add back classic signer

- master/doctest.py
This should speed things up slightly
> Don't bother precompiling when running doctests

- master/doctest.py
These properties weren't being parsed properly
> Properly Parse Properties

- master/builder_utils.py
We didn't use to always generate tarballs for all releases, but now that
we do, abandon `.dmg` mounting and extracting `.exe` files; instead just
use `curl | tar` on all platforms.
> Change Julia download strategy to just use tarballs on all platforms

- commands/rr_capture.jl
> Try to pass signal exits through the rr wrapper

- commands/rr_capture.jl
> Fix quoting in output capture script

- commands/rr_capture.jl
- Use better rr pack dir deduping (depends on https://github.com/JuliaPackaging/Yggdrasil/pull/2283)
- Switch to zstdmt for better compression throughput
- Clean up the temp dir before exiting
> Some tweaks to the script

- commands/rr_capture.jl
@staticfloat let's see if this works. It's possible this will slow down rr too much to work on CI, in which case we need to do something more targeted.
> Turn on rr logging to debug #39145

- master/package.py
> different fdinfo

- master/package.py
@vtjnash when you're done with this debugging, please merge this to get rid of those debugging statements.
> Remove fdinfo debugging

- master/coverage.py
> Add `download_url` default property

- master/doctest.py
- master/master.cfg
Also cleanup a very confusingly-named utility function
> Allow forcing doc deploys via the web interface

- master/master.cfg
> Allow ppc64le builder (not tester) to report

- master/doctest.py
Not sure if there's more stuff that needs to be commented out. cc @staticfloat
> Disable force_deploy_docs option

- commands/rr_capture.jl
This reimplements `Tar.create` for sufficiently old Julia versions to facilitate running rr for Julia pre-1.6. Should hopefully fix https://build.julialang.org/#/builders/71/builds/1091.
> Use tar CLI when Tar is not a stdlib

- commands/rr_capture.jl
Effectively reverts/redoes #194.
Most of the diff is increasing an indentation level, so I recommend adding &w=1 to the diff URL.
> Make rr a no-op for Julia < 1.6

- commands/rr_capture.jl
> Try to fix CI

- master/coverage.py
See also: https://github.com/JuliaLang/julia/pull/41103
This PR excludes all external stdlibs from code coverage.
Instead of hard-coding the list of external stdlibs, we auto-generate it.
https://github.com/JuliaLang/julia/pull/41103 is sufficient for Codecov. But Coveralls does not have a similar feature, so we need this code here.
This PR will take care of both Codecov and Coveralls. So once this PR is merged, we can merge https://github.com/JuliaLang/julia/pull/41112 (which reverts https://github.com/JuliaLang/julia/pull/41103).
> Code coverage: exclude all external stdlibs (and auto-generate the list of external stdlibs, instead of hard-coding it)

- master/coverage.py
Closes https://github.com/JuliaLang/julia/issues/41237
> Code coverage: exclude all stdlib JLLs from code coverage

- master/separated_testing.py
> Set the `OPENBLAS_NUM_THREADS` environment variable to `8` in the testers

- master/inventory.py
- master/master.cfg
Reverts JuliaCI/julia-buildbot#243
> Revert "Try adding an old branch canceller plugin"

- master/github_listener.py
Reverts JuliaCI/julia-buildbot#236
> Revert "Do not rerun all Buildbot jobs when someone closes and reopens a pull request"

- master/master.cfg
Something in #243 was broken, I think.
I reverted #243. Now, I'm going to try adding it back piece by piece to see what breaks.
> import SourceStampFilter

- master/master.cfg
@ararslan this should fix the source tarballs not getting uploaded.
> `-beta` and `-alpha` tags should be treated as protected as well

- master/package.py
> Use https to clone

- master/package.py
Alex's victory is finally complete
> Disable FreeBSD
