master/master.cfg, master/nightly_gc_debug.py
I use the nightly_llvmsvn build as a template to create this one. Right now this only enable the `WITH_GC_DEBUG_ENV` option in order to test if anything breaks the compilation of the gc debugging code and to check if anything obvious is broken in the test.
Ideally, there should be another bot that use the same build option (either building it or take it from this bot) and run the test suite with more aggressive GC collection.
=> Add gc_debug build

master/nightly_llvmsvn.py
The LLVM version doesn't seem to be shown anywhere else otherwise.
@staticfloat
=> Print versioninfo in llvm-svn build to get the llvm version number

master/coverage.py, master/master.cfg, master/nightly_noinline.py
Use a separate buildbot for noinline tests
Fix #55 
I realized that the test list is from `CoverageBase.jl` so this requires https://github.com/JuliaCI/CoverageBase.jl/pull/19 
@staticfloat
=> Only run coverage with inlining on

master/inventory.py, master/package_tarball.py
So that the default tripple is set to ARMv7 instead of ARMv8.
Thanks to @staticfloat for showing me the right API to pass this value as a property...
Assuming this does not break the buildbot setup (like, due to a syntax error....) I'm planing to test this by triggering a force build on a branch that sets the default LLVM version to 3.9 on arm (and do that on master if everything works ok).
=> Set `LLVM_CMAKE` on ARM buildbot

master/package.py
This target has no dependencies, so we probably want to fail-fast if it fails, so we can restart-fast. (@staticfloat)
=> move win-extra step early

master/package.py
Everybody do your share.
Should prevent the OSX buildbot from running out of space again.
=> Widen cleanup rules to include OSX and Linux as well

master/coverage.py
Try to add `stdlib/*/src` to the Coverage results. Not sure how to test this, so I could only made sure it parses. (@staticfloat)
=> process stdlib folders

master/inventory.py, master/package.py
I installed ccache on Windows and the mac bot. 
While deleting files on Windows will still be slow, this allows us 
more consistent builds (and builds for release-0.6)
=> Use ccache everywhere

master/inventory.py, master/package.py
Builds with ccache are better than from scratch, but they still take a
lot of time. Add stats so that we can monitor whether our cache is big enough
and increase the number of paralle make jobs.
=> Set -jN per machine and add stats for ccache

master/package.py
The default config seems quite small, but I will keep an eye on usage
for a couple more days before changing it.
=> ccache on windows doesn't have -p

master/auto_reload.py, master/builder_utils.py, master/coverage.py, master/llvm_extras.py, master/llvmjl.py, master/nightly_gc_debug.py, master/nightly_llvmsvn.py, master/nightly_srpm.py, master/nightly_threading.py, master/nuclear_arsenal.py, master/package.py, master/separated_testing.py, master/sign_juno.py
Using `/bin/bash` is problematic for systems such as FreeBSD, which do not have Bash preinstalled, and on which installing Bash does not create `/bin/bash`. There does not appear to be anything Bash-specific that we're using, so using regular POSIX `sh` should be just fine.
=> Run build steps with /bin/sh instead of /bin/bash

master/inventory.py
@vchuravy @yuyichao 
Just to double-check, this was a typo right?  There's no reason to have duplicate entries in this list?
=> Remove duplicate `armv7-a` entry in `JULIA_CPU_TARGET`

master/inventory.py
cc @staticfloat 
--
https://build.julialang.org/#/builders/67/builds/8
So, add it to the production worker list.
=> FreeBSD CI: worker gaebolg passed experimental run

master/coverage.py
This creates a symlink that will hopefully allow coverage results to be gathered.
=> Add ugly symlink workaround until https://github.com/JuliaLang/julia/issues/26314 is fixed

master/inventory.py
This worker passed the experimental run after the PR (https://github.com/JuliaLang/julia/pull/31046) merged.
It's a 12.0-RELEASE worker.
Exp run log: https://build.julialang.org/#/builders/67/builds/9
cc @staticfloat, @ararslan
=> FreeBSD CI: mark worker 'abeing' as a main worker

master/analyzegc.py, master/master.cfg
This runs the `clang` static analysis target to analyze Julia's C source.  Closes #118.  Won't run successfully until https://github.com/JuliaLang/julia/pull/32171 is merged.
=> Add `analyzegc` scheduler that gets run alongside normal packaging

master/coverage.py, master/doctest.py, master/llvmpasses.py, master/package.py, master/separated_testing.py, master/whitespace.py
Found this mentioned at http://docs.buildbot.net/latest/manual/configuration/buildsteps.html#using-shellcommands @staticfloat
=> send SIGTERM before SIGKILL

master/coverage.py
Currently, our coverage results are being impacted by including Pkg, even though we don't run the tests for it (we assume it has it's own test suite and coverage and releases—like any of our other vendored dependencies). There doesn't seem to be a good way to identify these right now, since we don't have vendored information in the build results. Maybe the Pkg folks have a plan for adding it. For now, this information doesn't change too often, so we should be alright with hard-coding it.
@staticfloat
=> Drop coverage results from Pkg and Statistics

master/inventory.py, master/separated_testing.py
We have not been passing these properly ever since we split into the
separated testing regime.  Fix the plumbing to hopefully make the
`armv7l` builders ever so slightly happier.
=> Fix passing of testing `MAXRSS` and `nthreads` parameters

master/inventory.py
@vchuravy @yuyichao can you guys weigh in and let me and @ianshmean know if this makes sense?
We read that we should not be using `-march` but should instead be using `-mcpu` for ARM code. [1]. So we switched to `-mcpu=arm7` and `-mcpu=arm8`, but that doesn't seem to work (at least GCC doesn't like them).  I know I can use `-mcpu=generic`, would that be better perhaps?
We also wanted to update the sysimg multiversioning on armv8, so Ian helpfully dug up some cpuid outputs and we jammed the flags into here as best we could, but we're not 100% certain these are right or even fully helpful.  If either of you have any input, that would be great.
[1] https://community.arm.com/developer/tools-software/tools/b/tools-software-ides-blog/posts/compiler-flags-across-architectures-march-mtune-and-mcpu …
=> Rework `cpu_targets` for armv7 and armv8

master/package.py
=> Cleanup zips on master

master/package.py
@musm does this look reasonable to you?
We also have two manual signing steps: [we sign `usr/bin/julia.exe`](https://github.com/JuliaCI/julia-buildbot/blob/master/master/package.py#L134-L140) and [the eventual `julia-x.y.z.exe` installer](https://github.com/JuliaCI/julia-buildbot/blob/master/master/package.py#L198-L206).  Do we still need to do either of those?
=> Add `INNO_ARGS` to automatically sign executables

master/package.py
Reverts JuliaCI/julia-buildbot#165
Won't be needing this starting from 1.5.3.
Although, it might not hurt to just leave it in.
=> Revert "Add back classic signer"

master/doctest.py
We were leaking big srcdist tarballs into `/tmp`.  Note to self; a better architecture for these things is to do all work in a folder namespaced by job ID, then just `rm -rf /tmp/${job_id}` at the end.  We should make sure buildkite makes it easy to do that.
=> Cleanup master after srcdist targets

master/coverage.py, master/separated_testing.py
=> Move coverage to a nightly schedule

commands/rr_capture.jl
This fixes an issue with the `dateformat` string macro, which doesn't expand properly at parse time unless Dates has been loaded.
Should fix the current 64-bit Linux failure on the 1.5.4 backports PR.
=> Unconditionally load Pkg and Dates

master/inventory.py, master/nightly_gc_debug.py, master/nightly_threading.py
Assumes make >= v4.0 from many years ago (n.b. this version is NOT available on macOS, which is v3.81)
=> Organize `make` output better

master/inventory.py
These are the only buildbot platforms that have `make` >= `v4`, it seems.
=> Only add `--output-sync=target` on Windows/FreeBSD

master/package.py
This propagates to the tarballs that we ship and also the packaged installer
When opening an issue, please ping @staticfloat
close: https://github.com/JuliaCI/julia-buildbot/issues/201
=> Add back code signing of the julia executable

master/package.py
This way, we notice if e.g. there are missing checksums.
=> If the working directory is not clean after `make install`, fail the build

master/master.cfg
Disable analyzegc and llvmpasses for now.
x-ref: https://buildkite.com/julialang/julia/builds/200
Should wait until we figure out why buildkite didn't trigger on
https://github.com/JuliaLang/julia/pull/40774#issuecomment-844657139
cc: @staticfloat
=> disable analyzegc&llvmpasses in favour of buildkite

master/coverage.py
This is only a short-term temporary fix to get coverage submission working again.
Long-term, I do want to get the "automatically generate the list of external stdlibs" feature working. Unfortunately, this feature requires that we have a checkout of the `JuliaLang/julia` source code, because we use the source code to generate the list (we look for files of the form `stdlib/*.version` as a way of identifying external stdlibs).
Right now, IIUC, the coverage buildbot doesn't actually have a checkout of the source code, so we'll need to figure out how to get the source code in order to get the automatic feature working.
Anyway, for now this PR hardcodes the list, and this should fix coverage submission.
=> Code coverage: TEMPORARILY hard-code the list of external stdlibs

master/inventory.py
For now, I'd like to add three new FreeBSD VMs. I haven't yet deleted the old VMs. So I'd like to add the new ones as 4,5,6.
=> Add `freebsd-x86_64-amdci6_4`, `freebsd-x86_64-amdci6_5`, and `freebsd-x86_64-amdci6_6`

master/inventory.py
See also:
- https://github.com/JuliaCI/julia-buildbot/pull/216
- https://github.com/JuliaLang/julia/issues/34627
=> A more correct way of passing the `USE_BINARYBUILDER_LIBUV=0` flag to`gmake` (only on FreeBSD)

master/inventory.py
1,2,3: the originals. FreeBSD11. Maybe there is something wrong with the VM disk images now?
4,5,6: FreeBSD12. Created from scratch today from a FreeBSD-12.2 ISO.
7,8,9: FreeBSD11. Created from scratch from a new FreeBSD-11 ISO.
=> Add some more FreeBSD11 workers, but created fresh

master/package.py
This is my attempt to fix the `package_win` buildbots by disabling code-signing.
If this works, it will just be a very short-term solution until we can fix code-signing.
cc: @staticfloat @musm @ararslan @KristofferC
=> `package_win`: TEMPORARILY disable code-signing

master/inventory.py
1. I shutdown the old workers that were running FreeBSD 11. These were the workers with names ending in `amdci6_1`, `amdci6_2`, `amdci6_3`.
2. I have started three new workers that are running FreeBSD 12. These workers have names ending in `amdci6_4`, `amdci6_5`, `amdci6_6`.
3. Since we are now using FreeBSD 12, we need to do `gmake USE_BINARYBUILDER_LIBUV=0`. For details, see:
- https://github.com/JuliaLang/julia/issues/34627
cc: @staticfloat @ararslan
=> Upgrade the FreeBSD buildbots to FreeBSD 12

master/package.py
We can revert this once BinaryBuilder has been updated to FreeBSD 12, which will fix the upstream issue that necessitates this.
=> Set `USE_BINARYBUILDER_LIBUV=0` on package_freebsd

master/inventory.py
We are now setting this in `package.py`, so we don't also need to set this in `inventory.py`.
=> Remove a redundant flag

master/master.cfg
Just for now. We'll revert this once `tester_freebsd64` is passing against on `master`.
=> Slack generator: TEMPORARILY don't post Slack messages for failures of `tester_freebsd64`

master/github_listener.py
Before this PR, when someone closes and reopens a pull request:
1. Buildkite reruns only the failed Buildkite jobs. If there are no failed Buildkite jobs, Buildkite does nothing.
2. Buildbot reruns all Buildbot jobs, whether they passed or failed.
After this PR, when someone closes and reopens a pull request:
1. Buildkite reruns only the failed Buildkite jobs. If there are no failed Buildkite jobs, Buildkite does nothing.
2. Buildbot does nothing.
After this PR is merged, if someone wants to retry a failed Buildbot job, they can ask a committer to log in to build.julialang.org and retry the job.
---
In the event that someone really does need to rerun all CI jobs, they can do either of the following:
1. Push a new commit.
2. Amend their last commit, and then force-push the amended commit. …
=> Do not rerun all Buildbot jobs when someone closes and reopens a pull request

master/separated_testing.py
Buildbot is actually already skipping these test sets. But that is not immediately obvious when you are reading this code. So let's make it explicit.
=> Make it explicitly clear that we are skipping the `Pkg` and `Pkg/pkg` test sets

master/separated_testing.py
`"all"` already includes `"download"`: https://github.com/JuliaLang/julia/blob/a121721f975fc4105ed24ebd0ad1020d08d07a38/test/choosetests.jl#L31
So we don't need to add it to the list again.
=> It is redundant to add `download` to the list of test sets

master/inventory.py, master/master.cfg
We want to cancel old builds on PRs but not on `master`, since we'd like to have a list of green checkmarks
=> Try adding an old branch canceller plugin

master/inventory.py
Let's try this out. If this works, then in a follow-up PR, we can figure out how to assemble this list of builder names programmatically.
=> `OldBuildCanceller`: hard-code a few example builder names

master/separated_testing.py
I keep seeing jobs that timeout at 4 hours, but they are nearly finished, e.g. they are running the "node 1 only" tests.
Here's an example: https://build.julialang.org/#/builders/17/builds/1484
=> Increase the tester timeout from 4 hours to 5 hours

master/package.py
I believe the keychain problems we're having now is due to us trying to use keychain objects in `make binary-dist`, and it worked so far because the keychains were remaining unlocked from previous CI runs.  😳  After the buildbots were restarted, everything stonewalled on the `make binary-dist` step, and the keychains were never unlocked.
=> Try unlocking keychain before `make binary-dist`

master/package.py
This should prevent us from doing linux64 builds on buildbot
=> Un-hook `linux64` from the CI build scheduler

master/master.cfg
We've been lacking nightlies ever since turning off the linux64
builders; this is because we used to us the linux64 builders as the
trigger to start all of our non-assert builds.  Let's switch it over to
win64 for now.
=> Fix missing windows builds

master/package.py
Since we have moved those two to Buildkite.
=> Turn off `package_linxux64` and `package_macos64`

master/package.py
While we correctly disabled initial builds, we didn't properly cleanup the triggered non-assert builds
=> Also disable triggered non-assert builds

master/package.py
Reverts JuliaCI/julia-buildbot#276
Just for a little while, so that Alex and Kristoffer can get 1.8.2 out the door.
=> Revert "Disable Windows builders!"

master/master.cfg
Now that we have decided to disable FreeBSD testing, that eliminates the final tester we've been using on buildbot, so let's just disable them all.
=> Disable _all_ testing on buildbot

master/package.py
=> Build non-assert builds by default
